### ISSUE TITLE
The code 

### ISSUE THREAD

**Issue by jahagirdar** [nejsan/gcalert#3]
The code throws an exception for my calendar
Logged in to Google Calendar
gcalert 3.2 running
Traceback (most recent call last):
  File "gcalert", line 647, in <module>
    GCalert()
  File "gcalert", line 209, in __init__
    self.update_events_thread()
  File "gcalert", line 398, in update_events_thread
    new_events = self.date_range_query(range_start.isoformat(), range_end.isoformat())
  File "gcalert", line 257, in date_range_query
    if not 'overrides' in event['reminders']:
KeyError: 'reminders'

**Comment by codehearts** [comment]
Hi, sorry to hear there are issues with this project! I haven't personally used it in a long while, so it's possible the API has changed since then. There was a fork of this project which had additional functionality added, but I can't find it anymore. I'll see if I can make time to dig into this and will let you know when I do!
